services:
  ## Network and DNS
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: "America/Sao_Paulo"
      WEBPASSWORD_FILE: /run/secrets/pihole-webpassword
    volumes:
      - ~/data/pihole/etc-pihole:/etc/pihole
      - ~/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    secrets:
      - pihole-webpassword

  nginx-proxy-manager:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8080:80"
      - "8443:443"
      - "81:81"
    volumes:
      - ~/data/npm/data:/data
      - ~/data/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - homelab

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 8383:8383 # qbittorrent ui
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
      - 9696:9696 # prowlarr
      - 8191:8191 # byparr
    volumes:
      - ~/data/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Sao_Paulo
      HEALTH_TARGET_ADDRESS: 1.1.1.1:443
      UPDATER_PERIOD: 24h
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING_UP_COMMAND: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8383/api/v2/app/setPreferences 2>&1'
      SERVER_COUNTRIES: Switzerland
      PORT_FORWARD_ONLY: on
      VPN_PORT_FORWARDING: on
    secrets:
      - openvpn-wireguard-private-key
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  # crontab-ui:
  #   image: alseambusher/crontab-ui
  #   container_name: crontab-ui
  #   restart: unless-stopped
  #   ports:
  #     - 8003:8000
  #   volumes:
  #     - ~/data/crontab:/crontab-ui/crontabs/

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "0"
    ports:
      - 3010:3000
    # environment:
    # GF_INSTALL_PLUGINS: influxdb Optional
    volumes:
      - ~/data/grafana:/var/lib/grafana

  influxdb2:
    image: influxdb:2
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  # MEDIA REQUESTER
  jellyseerr:
    image: ghcr.io/seerr-team/seerr:develop
    init: true
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Sao_Paulo
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    volumes:
      - ~/data/jellyseerr/config:/app/config
    restart: unless-stopped

  # INDEXER
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/prowlarr/config:/config
      - ./prowlarr:/config/Definitions/Custom
    network_mode: service:gluetun
    restart: unless-stopped

  # DDoS SOLVER
  # flaresolverr:
  #   image: flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 8191:8191
  #   restart: unless-stopped

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      # If you want to use Proxy
      # - PROXY_SERVER=
      # - PROXY_USERNAME=
      # - PROXY_PASSWORD=
      - TZ=America/Sao_Paulo
    network_mode: service:gluetun
    restart: unless-stopped

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    group_add:
      - ${DOCKER_GID:-992}
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/dockhand:/app/data

  # SUBTITLES
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/bazarr/config:/config
      - /media/Expansion/Media Server:/mediaserver
    ports:
      - 6767:6767
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/radarr/config:/config
      - /media/Expansion/Media Server:/movies
      - ~/downloaded-torrents/Completos:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/sonarr/config:/config
      - /media/Expansion/Media Server:/movies
      - ~/downloaded-torrents/Completos:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8383
    volumes:
      - ~/data/qbittorrent/config:/config
      - ~/downloaded-torrents/Completos:/downloads
    network_mode: service:gluetun
    restart: unless-stopped

  # Externally installed at moment
  # homeassistant:
  #   container_name: homeassistant
  #   image: "ghcr.io/home-assistant/home-assistant:stable"
  #   volumes:
  #     - ~/data/homeassistant/config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: unless-stopped
  #   privileged: true
  #   network_mode: host

secrets:
  influxdb2-admin-username:
    file: ~/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ~/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ~/.env.influxdb2-admin-token
  openvpn-username:
    file: ~/.env.openvpn-username
  openvpn-password:
    file: ~/.env.openvpn-password
  openvpn-wireguard-private-key:
    environment: WIREGUARD_PRIVATE_KEY
  pihole-webpassword:
    file: ~/.env.pihole-webpassword

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  homelab:
    driver: bridge
    external: true
