services:
  n8n:
    image: n8nio/n8n:1.121.0
    container_name: n8n
    environment:
      - TZ=America/Sao_Paulo
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - CREDENTIALS_OVERWRITE_ENDPOINT=send-credentials
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PATH=/
      - N8N_PUBLIC_API_ENDPOINT=api
    ports:
      - 5678:5678
    volumes:
      - ~/data/n8n:/home/node/.n8n
    restart: unless-stopped

  n8n-task-runners:
    build:
      context: .
      dockerfile: n8n/Dockerfile.runner
      args:
        - N8N_RUNNERS_VERSION=1.121.0
    container_name: n8n-runners
    environment:
      - N8N_RUNNERS_VERSION=1.121.0
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    depends_on:
      - n8n
