version: "3"

services:
  # TORRENT GUI
  flood:
    image: jesec/flood:master
    container_name: flood
    command: --port 6060 --allowedpath /data
    user: 1000:1000
    environment:
      HOME: /config
      TZ: America/Sao_Paulo
    ports:
      - 6060:6060
    volumes:
      - ~/data/flood/data:/data
      - ~/data/flood/config:/config
    restart: unless-stopped

  # MEDIA REQUESTER
  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Sao_Paulo
    ports:
      - 5055:5055
    volumes:
      - ~/data/jellyseerr/config:/app/config
    restart: unless-stopped

  # INDEXER
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # INDEXER
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true
    volumes:
      - ~/data/jackett/config:/config
      - ~/data/jackett/downloads:/downloads
    ports:
      - 9118:9117
    restart: unless-stopped

  # DDoS SOLVER
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Sao_Paulo
    ports:
      - 8191:8191
    restart: unless-stopped

  # SUBTITLES
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/bazarr/config:/config
      - ~/media:/mediaserver
    ports:
      - 6767:6767
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/radarr/config:/config
      - ~/media:/movies
      - ~/downloaded-torrents/Completos:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/data/sonarr/config:/config
      - ~/media:/movies
      - ~/downloaded-torrents/Completos:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8383
    volumes:
      - ~/data/qbittorrent/config:/config
      - ~/downloaded-torrents/Completos:/downloads
    ports:
      - 8383:8383
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
