ARG N8N_RUNNERS_VERSION

FROM n8nio/runners:${N8N_RUNNERS_VERSION}

USER root

RUN cd /opt/runners/task-runner-javascript && pnpm add moment uuid mal-scraper axios dayjs cheerio
RUN cd /opt/runners/task-runner-python && uv pip install numpy pandas requests beautifulsoup4
# COPY n8n-task-runners.json /etc/n8n-task-runners.json

USER runner